[build]
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/quarto-1.6.39-linux-amd64.tar.gz
    mkdir -p ~/opt
    tar -C ~/opt -xvzf quarto-1.6.39-linux-amd64.tar.gz
    export PATH=~/opt/quarto-1.6.39/bin:$PATH
    quarto render
  """
  publish = "_site"